---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: resource-web-app

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      go version
      echo "List whats in the current directory"
      ls -lat 
      echo ""
      # Setup the gopath based on current directory.
      export GOPATH=$PWD
      echo $GOPATH;
      pwd
      
      # Now we must move our code from the current directory ./resource-web-app to $GOPATHsrc/github.com/coxcs1/resource-web-app
      mkdir -p src/github.com/coxcs1/
      cp -R ./resource-web-app src/github.com/coxcs1/.
      # All set and everything is in the right place for go
      echo "Gopath is: " $GOPATH
      echo "pwd is: " $PWD
      echo ""
      # Put the binary filename in /built-project
      go build
      ls -lat
      echo ""
