---
resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/coxcs1/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: coxcs1@etsu.edu
    password: Dog.Bark1();
    organization: coxcs1-org
    space: development
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: resource-web-app, trigger: true}
  - task: build
    file: resource-web-app/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: resource-web-app/manifest.yml
      path: resource-web-app
